# Generated by Django 6.0.4 on 2026-04-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('ongoing', 'Ongoing'), ('pending', 'Pending'), ('completed', 'Completed')], max_length=20)),
            ],
        ),
    ]
